export const WORDS = [
  'apple', 'badge', 'blare', 'blend', 'bliss',
  'blitz', 'bluff', 'blush', 'brave', 'bride',
  'brisk', 'bunch', 'chair', 'charm', 'climb',
  'creek', 'crane', 'crave', 'crisp', 'crown',
  'douse', 'drain', 'drift', 'drown', 'dusky',
  'flock', 'flair', 'flash', 'flask', 'fleet',
  'flint', 'flute', 'frost', 'giant', 'glean',
  'glare', 'globe', 'glint', 'glove', 'grief',
  'grape', 'grind', 'happy', 'jumbo', 'latch',
  'lucky', 'lunar', 'mirth', 'moose', 'overt',
  'pluck', 'plaid', 'plumb', 'plush', 'pouch',
  'pride', 'prize', 'prong', 'quest', 'quake',
  'rider', 'scour', 'shear', 'shred', 'sling',
  'slope', 'smirk', 'snare', 'sneak', 'spark',
  'spear', 'squat', 'steak', 'sweep', 'swing',
  'swirl', 'swish', 'swarm', 'swoon', 'swoop',
  'throb', 'thump', 'torch', 'tiger', 'tramp'
];
